@url = http://localhost:8080/api/catalog
@id = c787acd5-aa1d-4138-be84-741d16da1385
@id2 = e41c8899-943b-4e16-9f6b-c1355a1088de
@id3 = 616264a8-a2ca-4584-b2a9-b2fab4c56a13


@del = e41c8899-943b-4e16-9f6b-c1355a1088de

###
GET {{url}}

###
GET {{url}}/{{id}}

###
GET {{url}}/{{id2}}

###
POST {{url}}
Content-Type: application/json

{
    "name": "Support",
    "description": "Customer support per month (IRR)",
    "price": 10000
}

###
POST {{url}}
Content-Type: application/json

{
    "name": "CPU",
    "description": "Central unit processor per hour (IRR)",
    "price": 1250
}

###
POST {{url}}
Content-Type: application/json

{
    "name": "RAM",
    "description": "Random access memory per hour (IRR)",
    "price": 780
}

###
DELETE {{url}}/{{del}}

###
PUT {{url}}/c787acd5-aa1d-4138-be84-741d16da1385
Content-Type: application/json

{
    "name": "Support",
    "description": "Customer support per month (IRR)",
    "price": 1000,
    "id": "c787acd5-aa1d-4138-be84-741d16da1385"
}